name: Create artifact

on:
  workflow_dispatch:

jobs:

  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ls
        run: |
          pwd
          ls -alh

      - name: Run ls in demo
        run: |
          cd demo
          pwd
          ls -lah

      - name: Create ZIP
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Create SHA256 checksum file
        uses:  ToxicAven/generate-checksum-file@v2
        with:
          filePath: release.zip
          saveFile: release.sha256sum
          algorithm: 'sha256'          

      - name: Run ls in artifact
        run: |
          pwd
          ls -lah
          cat release.sha256sum