name: Set up .NET

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - name: Show dotnet version
        run: dotnet --version
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: Upload dir
          path: demo
      - name: Upload S3
        uses: hkusu/s3-upload-action@v2
        id: S3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
          aws-region: 'us-east-1'
          public: false
          expire: 604800
          file-path: 'global.json'
          output-file-url: 'true'
      - name: Update URL
        run: | 
          URL='${{ steps.S3.outputs.file-url }}'
          echo $URL