name: Upload to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select an environment
        type: choice
        required: true
        default: "dev"
        options:
          - dev
          - qa
          - stg
          - pre
          - prod

  workflow_call:

jobs:

  env_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Environment check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"

          if [ "${{ inputs.environment }}" = "prod" ]; then
            echo "::set-output name=env_name::prod"
          elif [ "${{ inputs.environment }}" = "stg" ]; then
            echo "::set-output name=env_name::staging"
          elif [ "${{ inputs.environment }}" = "qa" ]; then
            echo "::set-output name=env_name::qa"
          elif [ "${{ inputs.environment }}" = "pre" ]; then
            echo "::set-output name=env_name::pre"
          else
            echo "::set-output name=env_name::dev"
          fi    
              
      - name: Use environment setup in previous step
        run: echo "Setting up environment ${{ steps.branch_check.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
 
  release_tag:
    needs: env_check
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.env_check.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print saltmaster
        run: echo ${{ vars.SALTMASTER }} 

      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
    
      - name: Deploy using stored timestamp
        run: echo "Deploying at $BUILD_TIME"

