name: Upload to S3

on:
  workflow_dispatch:

  workflow_call:

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: Upload dir
          path: demo

      - name: Upload S3
        uses: hkusu/s3-upload-action@v2
        id: S3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
          aws-region: 'us-east-1'
          public: false
          expire: 604800
          file-path: 'global.json'
          output-file-url: 'true'
      - name: Update URL
        env:
          S3_URL: ${{ steps.S3.outputs.file-url }}
        run: | 
          echo $S3_URL | sed 's/[*]\+/${{ secrets.AWS_BUCKET_NAME }}/'
          echo $S3_URL | sed 's/[*]\+/${{ secrets.AWS_KEY_ID }}/'
          echo $S3_URL