name: Deploy scrapers

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true

      environment:
        description: Select an environment
        type: choice
        required: true
        default: "dev"
        options:
          - qa
          - stg
          - pre
          - prod
          - dr

      app3:
        type: boolean
        description: Deploy on app3
        default: true

      app4:
        type: boolean
        description: Deploy on app4
        default: true

      app5:
        type: boolean
        description: Deploy on app5
        default: true

      app8:
        type: boolean
        description: Deploy on app8

      app9:
        type: boolean
        description: Deploy on app9

      app10:
        type: boolean
        description: Deploy on app10

  workflow_call:

env:
  APP_NAME: "scrapers"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Show dotnet version
        run: dotnet --version

  telegram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.workflow_run.head_commit.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
