name: Deploy scrapers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select an environment
        type: choice
        required: true
        options:
          - qa
          - stg
          - pre
          - prod
          - dr

      app3:
        type: boolean
        description: Deploy on app3
        default: true

      app4:
        type: boolean
        description: Deploy on app4
        default: true

      app5:
        type: boolean
        description: Deploy on app5
        default: true

      app8:
        type: boolean
        description: Deploy on app8
        default: true

      app9:
        type: boolean
        description: Deploy on app9
        default: true

      app10:
        type: boolean
        description: Deploy on app10
        default: true

  workflow_call:

env:
  APP_NAME: "scrapers"

jobs:

  prepare:
    name: Set Saltmaster
    runs-on: ubuntu-latest
    steps:
      - name: Check if prod
        if: ${{ inputs.environment == 'prod' }}
        run: echo "SALTMASTER=saltmaster.prod.reorg.int" >> $GITHUB_ENV

      - name: Configuration for qa branch
        if: ${{ inputs.environment == 'qa' }}
        run: echo "SALTMASTER=saltmaster.qa.reorg.int" >> $GITHUB_ENV

      - name: Configuration for stg branch
        if: ${{ inputs.environment == 'stg' }}
        run: echo "SALTMASTER=saltmaster.stg.reorg.int" >> $GITHUB_ENV

      - name: Configuration for pre branch
        if: ${{ inputs.environment == 'pre' }}
        run: echo "SALTMASTER=saltmaster.pre.reorg.int" >> $GITHUB_ENV


  build:
    needs: prepare
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Show dotnet version
        run: dotnet --version

  pillar:
    needs: build
    name: Pillar info
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment info
        run: echo "${{ toJson(inputs) }}"

  saltmaster:
    needs: pillar
    name: Saltmaster
    runs-on: ubuntu-latest
    steps:
      - name: Print Saltmaster info
        run: echo "${{ env.SALTMASTER }}"

  telegram:
    needs: saltmaster
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.workflow_run.head_commit.message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            This is passed to Saltmaster:
            ${{ toJson(inputs) }}
