name: Manual run of .NET

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true


      boolean:
        type: boolean
        description: True or False
            
      environment:
        description: Select an environment
        type: choice
        required: true
        default: 'dev'
        options:
        - dev
        - qa
        - stg
        - pre
        - prod

      tags:
        description: 'Test scenario tags'

env:
  DOTNET_VERSION: 
  DAY_OF_WEEK: Monday

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: '6.0.x'
        - name: Show dotnet version
          run: dotnet --version

  printInputs:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        
  greetingJob:
    name: Greeting Jobs
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: "Say Hello Mona it's Monday"
      if: ${{ env.DAY_OF_WEEK == 'Monday' }}
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      env:
        First_Name: Mona